# Generated by Django 4.0.5 on 2022-12-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0003_remove_course_goal_course_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='learner', to='kids.kid'),
        ),
    ]
