# Generated by Django 4.0.5 on 2022-12-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0006_alter_evaluation_qualified'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='img_URL',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='qualified',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='expectation',
            name='qualified',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='kid',
            name='status',
            field=models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Normal'), (4, 'Good'), (5, 'Excellent')]),
        ),
    ]
