# Generated by Django 4.0.5 on 2022-12-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0007_course_category_course_img_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='starting_date',
            field=models.DateField(blank=True),
        ),
    ]
