# Generated by Django 4.0.5 on 2022-12-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0008_alter_course_starting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='cog_int',
            field=models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Normal'), (4, 'Good'), (5, 'Excellent')], default=3),
        ),
        migrations.AddField(
            model_name='kid',
            name='gender_growth',
            field=models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Normal'), (4, 'Good'), (5, 'Excellent')], default=3),
        ),
        migrations.AddField(
            model_name='kid',
            name='language_communication',
            field=models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Normal'), (4, 'Good'), (5, 'Excellent')], default=3),
        ),
        migrations.AddField(
            model_name='kid',
            name='motor',
            field=models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Normal'), (4, 'Good'), (5, 'Excellent')], default=3),
        ),
        migrations.AddField(
            model_name='kid',
            name='physical_growth',
            field=models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Normal'), (4, 'Good'), (5, 'Excellent')], default=3),
        ),
        migrations.AddField(
            model_name='kid',
            name='race',
            field=models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Normal'), (4, 'Good'), (5, 'Excellent')], default=3),
        ),
        migrations.AddField(
            model_name='kid',
            name='social_emotional',
            field=models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Normal'), (4, 'Good'), (5, 'Excellent')], default=3),
        ),
    ]
