# Generated by Django 4.0.5 on 2022-12-11 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0009_kid_cog_int_kid_gender_growth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creators', to=settings.AUTH_USER_MODEL),
        ),
    ]
