# Generated by Django 4.0.5 on 2022-12-28 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0010_kid_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_to_spend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_left', to='kids.course')),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timing', to='kids.kid')),
            ],
        ),
    ]
